### ISSUE TITLE
Errors while simulating FlexRay example tests

### ISSUE THREAD

**Issue by RaoShri** [CoRE-RG/FiCo4OMNeT#5]
Hello guys,
I am new to this environment, and I tried to run your example tests for CAN and FlexRay. I am facing errors while running FlexRay example codes. Could you give me a solution? CAN examples are going through.

Also, is there a way to print packets during the simulation? I was unable to install osg-earth, I guess that's why the sequence chart is not opening for me. Any tips would be really helpful. 
Error message : 

**<!> Error: (omnetpp::cModule)frBus: Gate index 0 out of range when accessing vector gate 'channelA$i[]' with size 0, at /home/shrinidhi/git/FiCo4OMNeT/examples/flexray/dynamic/dynamic.ned:49 -- in module (omnetpp::cModule) dynamic (id=1), during network setup

End.

Simulation terminated with exit code: 1
Working directory: /home/shrinidhi/git/FiCo4OMNeT/examples/flexray/dynamic
Command line: opp_run -m -c General -n ../..:../../../examples_andl:../../../simulations:../../../src -l ../../../src/FiCo4OMNeT u1.ini**

**Comment by Musteblume** [comment]
Hi,

i just tested the dynamic example again and there are no problems for me.
How is your Setup? (OS, OMNeT++ Version)

When you simulate with Qtenv you should see the packets if you click on "show message/packet traffic" in the bottom view:
https://doc.omnetpp.org/omnetpp/UserGuide.pdf - section 7.5.6

We don't use osg-earth in our models. So, it is fine to turn it off.

**Comment by RaoShri** [comment]
I am working in Kali Linux 5.10.0-kali3-amd64, 
Omnetpp Version: 5.6.2, Build id: 200518-aa79d0918f

**Comment by THaeckel** [comment]
Hi RaoShri, our simulation models are developed and tested for OMNeT++ version 5.5.1. Is it possible that you try it with this version and see if the error persists? You can find it at https://omnetpp.org/download/old.

**Comment by RaoShri** [comment]
Hi Thaekel,
It is working in omnetpp5.5.1. Thanks for your help.
