### ISSUE TITLE
Difference between rxDFLatency and rxDFPayloadLatency

### ISSUE THREAD

**Issue by franc444** [CoRE-RG/FiCo4OMNeT#6]
Hi, 

I did not really get the difference between `rxDFLatency` and `rxDFPayloadLatency` in `CanTrafficSinkApp` stats, and which one should I rely on if I want to get the end-to-end latency of CAN message? 

Thanks,

**Comment by franc444** [comment]
@Musteblume Thank you. 
So, in case we have gateways, then the `rxDFPayloadLatency `should be larger than `rxDFLatency`, right?

**Comment by Musteblume** [comment]
Hi,

yes: if the gateway is encapsulating the CAN payload into a new CAN message.
 no: if the gateway forwards complete can messages.
 
Best regards

**Comment by franc444** [comment]
Do you mean if the gateway forwards the complete CAN message, then `rxDFPayloadLatency` would be smaller than `rxDFLatency`? or they would have same values?

**Comment by Musteblume** [comment]
If creation time is the same and the gateway forwards complete CAN messages both latencies should have the same values.
I don't think there is any reasonable scenario where `rxDFPayloadLatency` is smaller than `rxDFLatency`.

**Comment by franc444** [comment]
Thank you. 
Does the same apply to remote frame with no payload?

**Comment by Musteblume** [comment]
You're welcome.
Yes, this should apply to all messages.
Best regards

**Comment by franc444** [comment]
Thank you!
